
language: cpp
sudo: require

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-6.0

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc8
        apt:
          sources: *all_sources
          packages: 
            - g++-8
      env:
        - MATRIX_EVAL="export CC=gcc-8; export CXX=g++-8;"

    - os: linux
      compiler: clang
      addons:
          apt:
              sources: *all_sources
              packages:
                - g++-8
                - clang-6.0
      env:
        - MATRIX_EVAL="export CC=clang-6.0; export CXX=clang++-6.0;"

before_install:
  # Update compilers
  - eval "${MATRIX_EVAL}"
  - echo "CC=$CC CXX=$CXX"
  # Install a supported cmake version (>= 3.14)
  - wget -O cmake.sh https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.sh 
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  # Build and install
  - export PATH=/usr/local/bin:$PATH
  - cmake --version
  - cmake -H. -Bbuild -DGLUE_BUILD_DUKTAPE=true -DGLUE_BUILD_LUA=true -DGLUE_ENABLE_LUA=true -DGLUE_ENABLE_DUKTAPE=true
  - cmake --build build
  - sudo cmake --build build --target install

script:
  - cmake -Htests -Bbuild/tests
  - cmake --build build/tests
  - CTEST_OUTPUT_ON_FAILURE=1 cmake --build build/tests --target test
 