name: MacOS

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -Htest -Bbuild -DUSE_SANITIZER='address;undefined'

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug
